server:
  port: 8081

spring:
  application:
    name: aura-read-service
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        service: ${spring.application.name}
        fail-fast: false
  datasource:
    url: jdbc:postgresql://localhost:5432/aura
    username: root
    password: 123456
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: 123456
      database: 0
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 100
          max-idle: 50
          min-idle: 10
          max-wait: 1000ms

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.aura.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com.aura.mapper: debug
